#!/bin/bash
# Routing (packet forwarding) enables a computer to communicate with other computers that are not on the same network or subnet.
# Router is connected to at least two networks and makes decisions about where to send the packets it receives based on the destination address.
# A gateway is the entrance point to another network. 
# A default gateway is the address to which packets are sent if there is no specific gateway for a given destination listed in the routing table.

# netstat -nr | grep "default" | head -1

route -n get default