#!/bin/bash
# traceroute uses Internet Control Message Protocol's Ping command 
# to find out how many different devices are between the computer initiating the traceroute and the target
traceroute who.int