#!/bin/bash
# Find the IP that was assigned to you by dhcp server.
ipconfig getpacket en0 | grep yiaddr | cut -d " " -f3

# yiaddr: The IP address assigned to the specified network interface on the system
# from which the command was issued.

# getpacket: Prints to standard output the DHCP packet that the
# client accepted from the DHCP/BOOTP server.
# This command is useful to check what the server provided,
# and whether the values are sensible.