#!/bin/bash
# yiaddr: The IP address assigned to the specified network interface on the system from which the command was issued.
#ifconfig en0 | grep inet | cut -d " " -f2
ipconfig getpacket en0 | grep yiaddr | cut -d " " -f3