#!/bin/bash
# What command can you use to rename your system?
sudo hostname newdebian

# To change the system name, I have to be superuser
# To become s superuser, run command: su -
# Then change the system name by running the command hostname newdebian
# To logout as superuser, run command: exit