#!/bin/bash
# command that shows for how long the system has been up and running since the last boot
uptime
# last reboot - all the previous reboot date and time for the system
# who -b - the last system reboot date and time