#!/bin/bash
# PID (Process ID) = created at SSHD startup time; read from the file and used to identify the sshd to terminate
cat /var/run/sshd.pid

# SSHD = Secure Shell Daemon application, daemon program for ssh 
# SSHD provides encrypted communications between two untrusted hosts over an insecure network
# SSHD is the daemon that listens for connections from clients on port 22