#!/bin/bash
du -sh /var/*
# Run the command above as root user
# s - display the total size of the specified directory, do not display file size totals for subdirectories
# h - human-readable format
# Two other options:
# du -shc /var/* - in addition to sizes of subdirectories, it shows also grand total of all sizes
# du -h --max-depth=1 /var - shows only the subdirectories with size greater than 0