#!/bin/bash
# Find the command that kills the background command’s process
sudo pkill -9 tail
# -9 - force terminates the process with the specified process name
# another option: kill %tail --> results in slight difference when running jobs command after killing the process
