#!/bin/bash
echo "Welcome to Love Crush Calculator!"
echo "Enter your name: "
read name1
echo "Enter your crush's name: "
read name2
ranNum=$(($RANDOM % 100 + 1))

case $(($ranNum)) in
([1-9]|[1-3][0-9]) echo "You and $name2's love percentage is $ranNum%. Just forget it!";;
([4-7][0-9]) echo "You and $name2's love percentage is $ranNum%. You might have a chance!";;
([8-9][0-9]|100) echo "You and $name2's love percentage is $ranNum%. Definitely go for it!";;
esac